name: web-character-project CI/CD
on:
  push:
    branches: [master]
jobs:
  CI:
    name: web-character-project CI/CD
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      # ec2프리티어에서 리엑트 빌드를 할수 없다,
      # 깃헙액션을 이용해서 빌드한 다음, ec2로 빌드폴더를 보내주는 방법이다.
      - name: Build React
        run: |
          cd ./client
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          npm i
          npm run build

      - name: Sending build foler to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./client/build/*"
          strip_components: 1
          target: "./git"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: ./deploy.sh
