name: web-character-project CI/CD
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build react app in docker of github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Set up node
      - uses: actions/setup-node@v3
      - with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Build react app, config environment variable
      - run: |
          cd client
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          npm i
          npm run build

      - name: Sending build foler to ec2
      - uses: appleboy/scp-action@master
      - with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          target: "/git/web-character-project/client/build"

      - name: Deploy
      - uses: appleboy/ssh-action@master
      - with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./deploy.sh
